[package]
name = "mach"
authors = ["intrepidpig"]
version = "0.0.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
json = { version = "1.0", package = "serde_json" }